version: "3.7"

services:
  pen-server:
    build: .
    container_name: pentaho
    networks:
      - etl_pentaho
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./local:/root/.kettle
    environment:
      - TZ=America/Sao_Paulo
  
  postgres:
    image: postgres:15
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432

networks:
  etl_pentaho:
