version: "3.7"

services:
  pentaho-data-integration:
    build: .
    container_name: pentaho
    networks:
      - etl_pentaho
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./local:/root/.kettle
    environment:
      - TZ=America/Sao_Paulo

  postgres:
    image: postgres:15
    container_name: postgres_pentaho
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      LANG: pt_BR.utf8
    ports:
      - 5432:5432
    networks:
      - etl_pentaho

  pgadmin:
    image: dpage/pgadmin4:7.8
    profiles:
      - "pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    depends_on:
      - postgres
    ports:
      - "9000:80"
    networks:
      - etl_pentaho

networks:
  etl_pentaho:
